### ISSUE TITLE
ql:quickload doesn't load cl-sqlite

### ISSUE THREAD

**Issue by kozross** [quicklisp/quicklisp-client#111]
When I call ``(ql:quickload 'cl-sqlite)``, I get the following error: ``System "cl-sqlite" not found``.

**Comment by quicklisp** [comment]
There isn't any system by that name. What did you expect to happen?

**Comment by kozross** [comment]
Does that mean there's an issue with Quickdocs? [They seem to disagree][1].

[1]: http://quickdocs.org/cl-sqlite/

**Comment by quicklisp** [comment]
I think Quickdocs is confusing in this case. The overall project is called "cl-sqlite". But the project has a system file named just "sqlite.asd", so that's the system that cl-sqlite provides. It would be good if Quickdocs clarified the distinction.

You can check by doing (ql:system-apropos "sqlite"). The leftmost thing is the system name you can load.
