### ISSUE TITLE
Update add-to-init-file to accept a :prompt keyword argument

### ISSUE THREAD

**Issue by quicklisp** [quicklisp/quicklisp-client#23]
For non-interactive use of add-to-init file, provide the ability to pass :prompt nil.

**Comment by Halfwake** [comment]
There's several ways to go about this and they're all annoying.

* Mix optional and keyword arguments. This is bad because the optional argument has to be given.
* Use an optional argument for prompt instead of a key argument. This is bad because the optional argument has to be given.
* Change `add-to-init-file` to use keyword arguments only. This is bad because it will break code.
* Expose `without-prompting` to the user. This is bad because it exposes a symbol that no one should need to know about.
* Create another function that wraps `add-to-init-file`, but with `*do-not-prompt*` shadowed. This is bad because now a new symbol has to be exposed and what should be in one function is now split across two.

I'll implement one of these later if nobody beats me to it or has any suggestions.

**Comment by quicklisp** [comment]
`without-prompting` is supposed to be external and part of the QL interface.

**Comment by Halfwake** [comment]
Oh, good! Then no prompt argument is needed.
